agent: ["AI"]
screen: [[640, 360], [320, 180], 'black']
font: ['Comic Sans MS', 8]
framerate: [60]
movement: [1.5, 5]
gravity: [2.3, 14, 16.8]
jumping: [0.55, 14, 24]
climbing: [110, 20, 10, 45.45, -0.8, 1.4]
dashing: [4, 0.25, 3.4, -0.5]
crystal: [2.6, 3, 0.15]
level: [[16, 156], [312, 69], True, -1]